### ISSUE TITLE
Downloads fail for princeton-rr172158w

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulmap#862]
When attempting to download the vector data set, the user interface breaks:

![image](https://user-images.githubusercontent.com/1443986/88235019-ff86f380-cc47-11ea-9b6b-7d4919556b01.png)

**Comment by jrgriffiniii** [comment]
This does not seem to break after I attempted to view this in Brave after breaking the UI in Chrome:

![image](https://user-images.githubusercontent.com/1443986/88235421-d87cf180-cc48-11ea-9ca7-2bf7c0a74ef3.png)

**Comment by jrgriffiniii** [comment]
Downloading the "Original Shapefile" seems to be working, as the Shapefile was valid when I downloaded this to my local macOS environment:

```
shapefile_rr172158w % ogrinfo -listmdd ./Global_3G_201612.shp
INFO: Open of `./Global_3G_201612.shp'
      using driver `ESRI Shapefile' successful.
1: Global_3G_201612 (Polygon)
shapefile_rr172158w % ogrinfo -al ./Global_3G_201612.shp | head -25
INFO: Open of `./Global_3G_201612.shp'
      using driver `ESRI Shapefile' successful.

Layer name: Global_3G_201612
Metadata:
  DBF_DATE_LAST_UPDATE=2017-02-22
Geometry: Polygon
Feature Count: 2412459
Extent: (-179.999989, -53.757229) - (179.999989, 78.383380)
Layer SRS WKT:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
SOURCE: String (20.0)
CNTRY_COV: String (10.0)
CNTRY_CODE: Real (19.11)
COUNTRY: String (60.0)
CNTRY_ISO: Integer64 (10.0)
```

**Comment by jrgriffiniii** [comment]
However, none of the derivatives could be downloaded for the file:

![image](https://user-images.githubusercontent.com/1443986/88236447-0cf1ad00-cc4b-11ea-8b81-c09be86da834.png)

**Comment by jrgriffiniii** [comment]
Attempting to refresh the browser window led to various errors, and attempting to restart the GeoServer installation did not resolve the problems encountered for this record.

**Comment by jrgriffiniii** [comment]
Attempting to view publicly accessible Documents published by Princeton, I am finding that Leaflet is breaking given that CORS headers are not provided for the WMS responses:

![image](https://user-images.githubusercontent.com/1443986/88237733-dd906f80-cc4d-11ea-8c12-16e1cb8b8edb.png)

**Comment by jrgriffiniii** [comment]
GeoServer is now inaccessible:

![image](https://user-images.githubusercontent.com/1443986/88238247-25fc5d00-cc4f-11ea-9e93-06af523d8965.png)
Please note that I am accessing this over the VPN.

**Comment by jrgriffiniii** [comment]
GeoServer has been restarted, but the following error is logged:

```
2020-07-22 19:18:14,326 ERROR [map.png] - Failed to encode the PNG
ar.com.hjg.pngj.PngjOutputException: org.geoserver.ows.ClientStreamAbortedException
        at ar.com.hjg.pngj.PngHelperInternal.writeBytes(PngHelperInternal.java:196)
        at ar.com.hjg.pngj.chunks.ChunkRaw.writeChunk(ChunkRaw.java:97)
        at ar.com.hjg.pngj.PngIDatChunkOutputStream.flushBuffer(PngIDatChunkOutputStream.java:28)
        at ar.com.hjg.pngj.ProgressiveOutputStream.checkFlushBuffer(ProgressiveOutputStream.java:65)
        at ar.com.hjg.pngj.ProgressiveOutputStream.flush(ProgressiveOutputStream.java:28)
        at ar.com.hjg.pngj.PngWriter.end(PngWriter.java:400)
        at it.geosolutions.imageio.plugins.png.PNGWriter.writePNG(PNGWriter.java:92)
        at org.geoserver.wms.map.png.PNGJWriter.writePNG(PNGJWriter.java:51)
        at org.geoserver.wms.map.PNGMapResponse.formatImageOutputStream(PNGMapResponse.java:104)
        at org.geoserver.wms.map.RenderedImageMapResponse.write(RenderedImageMapResponse.java:123)
        at org.geoserver.ows.Dispatcher.response(Dispatcher.java:1009)
```

**Comment by jrgriffiniii** [comment]
Redeploying `pulmap` did restore service, but I receive a different error message when attempting to download derivatives:

![image](https://user-images.githubusercontent.com/1443986/88238976-1c73f480-cc51-11ea-8992-6f6e15e6db83.png)

**Comment by jrgriffiniii** [comment]
This is being triggered by the following error on GeoServer:

```
abstractQueryExpression[0]:
        typeNames[0] = {http://restricted-figgy}p-c3618d35-d02a-4e84-bc57-cefe10d90934
        srsName = EPSG:4326
2020-07-22 19:27:54,686 INFO [wfs.json] - about to encode JSON
2020-07-22 19:27:58,037 ERROR [geoserver.ows] -
org.geoserver.platform.ServiceException: This request used more time than allowed and has been forcefully stopped. Max rendering time is 60.0s
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:576)
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:276)
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:139)
```

**Comment by jrgriffiniii** [comment]
There are also additional error messages which I keep receiving in the GeoServer logs:

```
2020-07-22 19:45:28,206 INFO [geoserver.gwc] - Error dispatching tile request to GeoServer
org.geowebcache.GeoWebCacheException: Problem communicating with GeoServer
```

**Comment by jrgriffiniii** [comment]
Nothing seems invalid with the Figgy Resource: https://figgy.princeton.edu/catalog/6f14c1a5-34d1-4fc3-b8e7-f481cf03d195

**Comment by jrgriffiniii** [comment]
After several attempts to restart GeoServer, I could not manage to connect to the server from lib-adc1:

```
pulsys@lib-adc1:~$ curl -I http://libserv21.princeton.edu:8080/
```

Please note that Tomcat was running on libserv21:

```
pulsys@libserv21:/var/log/tomcat8$ sudo systemctl status tomcat8.service
● tomcat8.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat8; bad; vendor preset: enabled)
   Active: active (running) since Wed 2020-07-22 20:54:45 EDT; 2min 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 103488 ExecStop=/etc/init.d/tomcat8 stop (code=exited, status=0/SUCCESS)
  Process: 103528 ExecStart=/etc/init.d/tomcat8 start (code=exited, status=0/SUCCESS)
    Tasks: 105
   Memory: 1.2G
      CPU: 3min 17.257s
   CGroup: /system.slice/tomcat8.service
           └─103553 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManage
Jul 22 20:54:40 libserv21 systemd[1]: Starting LSB: Start Tomcat....
Jul 22 20:54:40 libserv21 tomcat8[103528]:  * Starting Tomcat servlet engine tomcat8
Jul 22 20:54:45 libserv21 tomcat8[103528]:    ...done.
Jul 22 20:54:45 libserv21 systemd[1]: Started LSB: Start Tomcat..
```

...and that the GeoServer app was running:
```
22-Jul-2020 20:54:47.532 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
22-Jul-2020 20:54:47.533 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:47.535 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:47.536 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:48.686 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
```

**Comment by jrgriffiniii** [comment]
The `Max rendering time (s)` has been increased from 60s to 6000s:

![image](https://user-images.githubusercontent.com/1443986/88246147-a7f88000-cc67-11ea-9354-413812849cd7.png)

Unfortunately, this does not seem to have fully resolved the issue, as the `Faraday` client seems to just time out:

```
2020-07-22 21:59:40,263 INFO [geoserver.wfs] -
Request: getFeature
    service = wfs
    version = 2.0.0
    baseUrl = http://geoserver-prod:80/geoserver/
    outputFormat = SHAPE-ZIP
    resolve = none
    resolveDepth = *
    resolveTimeout = 300
    resultType = results
    abstractQueryExpressionGroup[0] = wfs:abstractQueryExpression=net.opengis.wfs20.impl.QueryTypeImpl@6cf31b98 (handle: null) (abstractProjectionClause: null, abstractSelectionClause: null, abstractSortingClause: null, aliases: null, typeNames: [{http://restricted-figgy}p-c3618d35-d02a-4e84-bc57-cefe10d90934]) (featureVersion: null, srsName: EPSG:4326, filter: null, propertyNames: null, sortBy: null)
    abstractQueryExpression[0]:
        typeNames[0] = {http://restricted-figgy}p-c3618d35-d02a-4e84-bc57-cefe10d90934
        srsName = EPSG:4326
2020-07-22 22:00:40,672 WARN [servlet.PageNotFound] - No mapping found for HTTP request with URI [/geoserver/restricted-figgy/pul-logo-new.svg] in DispatcherServlet with name 'dispatcher'
2020-07-22 22:00:51,155 INFO [geoserver.servlets] - OutputStream was successfully aborted.
```

**Comment by jrgriffiniii** [comment]
As of 09:44 EDT, GeoServer does seem to be serving vector datasets for Princeton Documents:

![image](https://user-images.githubusercontent.com/1443986/88293591-32250080-ccc9-11ea-835e-9a7662603918.png)

**Comment by jrgriffiniii** [comment]
The KMZ derivatives now seem to be generating:

![image](https://user-images.githubusercontent.com/1443986/88294175-efaff380-ccc9-11ea-961f-f29c5476df49.png)

**Comment by jrgriffiniii** [comment]
The GeoJSON download is functioning properly as well, however the Shapefile derivative is still failing for this:

![image](https://user-images.githubusercontent.com/1443986/88295209-1a4e7c00-cccb-11ea-8c32-368cfb7705f4.png)

**Comment by jrgriffiniii** [comment]
Attempting to manually place a Shapefile into the `/tmp/cache/downloads` directory does *not* serve the file from this interface.

**Comment by jrgriffiniii** [comment]
The correct directory is `/opt/pulmap/shared/maplab/pulmap/downloads`, I am uploading the file now.

**Comment by jrgriffiniii** [comment]
Uploading the Shapefile manually restored downloads for this derivative:

![image](https://user-images.githubusercontent.com/1443986/88301750-04dd5000-ccd3-11ea-8816-4b048ae47d66.png)
