### ISSUE TITLE
Private layers are missing from the figgy-restricted Workspace for GeoServer

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulmap#865]
I am seeing intermittent errors in the GeoServer logs, such as:

```
Request: getServiceInfo
2020-07-22 19:46:15,141 ERROR [geoserver.ows] -
org.geoserver.platform.ServiceException: Could not find layer restricted-figgy:p-426a478c-957d-4067-ab03-5c2944ca3187
        at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1341)
        at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:236)
        at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:85)
        at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1521)
        at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:680)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:258)
```

This would be triggered by a failure to synchronized Figgy Resources and the GeoServer REST API.

**Comment by jrgriffiniii** [comment]
GeoServer keeps crashing with the following error message:

```
org.geowebcache.GeoWebCacheException: Problem communicating with GeoServer                                                                                                              [144/164]
        at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:611)
        at org.geoserver.gwc.layer.GeoServerTileLayer.getTile(GeoServerTileLayer.java:554)
        at org.geoserver.gwc.GWC.dispatch(GWC.java:718)
```

GeoWebCache is coupled by default with GeoServer, but it can also be used to deploy GeoServer in a clustered configuration. I'm afraid that I would need to diagnose the GeoWebCache configuration settings in order to further progress with this.

**Comment by jrgriffiniii** [comment]
After several attempts to restart GeoServer, I could not manage to connect to the server from lib-adc1:

```
pulsys@lib-adc1:~$ curl -I http://libserv21.princeton.edu:8080/
```

Please note that Tomcat was running on libserv21:

```
pulsys@libserv21:/var/log/tomcat8$ sudo systemctl status tomcat8.service
● tomcat8.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat8; bad; vendor preset: enabled)
   Active: active (running) since Wed 2020-07-22 20:54:45 EDT; 2min 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 103488 ExecStop=/etc/init.d/tomcat8 stop (code=exited, status=0/SUCCESS)
  Process: 103528 ExecStart=/etc/init.d/tomcat8 start (code=exited, status=0/SUCCESS)
    Tasks: 105
   Memory: 1.2G
      CPU: 3min 17.257s
   CGroup: /system.slice/tomcat8.service
           └─103553 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManage
Jul 22 20:54:40 libserv21 systemd[1]: Starting LSB: Start Tomcat....
Jul 22 20:54:40 libserv21 tomcat8[103528]:  * Starting Tomcat servlet engine tomcat8
Jul 22 20:54:45 libserv21 tomcat8[103528]:    ...done.
Jul 22 20:54:45 libserv21 systemd[1]: Started LSB: Start Tomcat..
```

...and that the GeoServer app was running:
```
22-Jul-2020 20:54:47.532 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
22-Jul-2020 20:54:47.533 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:47.535 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:47.536 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
22-Jul-2020 20:54:48.685 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
22-Jul-2020 20:54:48.686 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
```
